# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# For pngquant see: https://pngquant.org


repos:
  - repo: https://github.com/gdubicki/pre-commit-pngquant
    rev: v2.1.0  # Use the sha / tag you want to point at
    hooks:
      - id: pngquant
        # args: [--speed=1] # these are optional
        args: [--quality=80, --speed=1, --max=1M]
        # Output an error message if the file is larger than 1MB
        error_message: "The PNG file is larger than 1MB. Please compress it using an image editor before committing."
        